apiVersion: v1
kind: Service
metadata:
  name: gamenet-service
spec:
  type: NodePort
  ports:
  - port: 44663
    targetPort: 44663
    protocol: UDP
    nodePort: 30663
  selector:
    app: gamenet-app
